#!/usr/bin/env bash
# display the content of the file /etc/passwd, using the while loop

while IFS=':' read -r username password uid gid info home shell; do
 "lives in $home and rides $shell"\
 "$uid's place is protected by the passcode $password,"\
 "more info about the user here: $info"
done < "/etc/passwd"
